deploymentName: "{{ vault://awssecretsmanager/prod/deployment-name#deploymentName }}"

replicaCount: 1

image:
  repository: alpine
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    memory: "64Mi"
    cpu: "250m"

containerPort: 80
command: ["/bin/sh", "-c"]
args: ["while true; do echo hello; sleep 10; done"]