apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bar-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-username/argocd-helm-secrets'
    targetRevision: HEAD
    path: 'bar-chart'
    helm:
      valueFiles:
        - values.yaml
    plugin:
      name: argocd-vault-plugin-helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
